### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by maacl** [kwrooijen/tauri-cljs#1]
From project.clj:

:license {:name "MIT"
            :url "https://www.eclipse.org/legal/epl-2.0/"}

**Comment by kwrooijen** [comment]
Whoops! I'll fix that

**Comment by maacl** [comment]
Of course it is entirely up to you, but I would recommend MIT :-)

**Comment by kwrooijen** [comment]
Thanks for letting me know. Fixed it in https://github.com/kwrooijen/tauri-cljs/commit/e7329a03122076d18ca2f5dbcc32973e1cabd591
